---
title: "Data processing"
author: "chris"
date: "09/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Data pre-processing 
```{r}
rm(list = ls())
train <- read.table('train2.txt',sep = ',',header = TRUE)
test <- read.table('test2.txt',sep = ',',header = TRUE)

```

##Dealing with Age
```{r}
age <- train$age

#if age is an interval then we define it as mean
for (i in 1:length(age)) {
  if (grepl('-',age[i])) {
    z = strsplit(age[i], '-')
    age[i] = mean (as.numeric(c(z[[1]][1],z[[1]][2])))
  }
}

age <- as.numeric(age)
mu <- mean(age[!is.na(age)])
library(tidyverse)
age = replace_na(age,mu)

#age = as.numeric(age)
for (i in 1:length(age)) {
  if (is.na(age[i]) || age[i] == '') {
    age.missing[i] =1
  }
}

all.age <- as.data.frame(cbind(age))
```

#dealing with sex
#we convert all features to indictor vriables
```{r}
#we only select those feature both appear in train and test
intersect_feature = union(train$sex,test$sex)
intersect_feature

sex = train$sex

sex.38fc4 = rep(0, nrow(train))
sex.8a467 = rep(0, nrow(train))
sex.d516d = rep(0, nrow(train))
sex.f7f7c = rep(0, nrow(train))
sex.1e6ee = rep(0, nrow(train))
sex.missing = rep(0, nrow(train))

for (i in 1:length(sex)) {
  if (grepl('38fc4',sex[i])) {sex.38fc4[i] = 1}
  else if (grepl('8a467',sex[i])) {sex.8a467[i] = 1}
  else if (grepl('d516d',sex[i])) {sex.d516d[i] = 1}
  else if (grepl('f7f7c',sex[i])) {sex.f7f7c[i] = 1}
  else if (grepl('1e6ee',sex[i])) {sex.1e6ee[i] = 1}
  else if (is.na(sex[i])) {sex.missing[i] = 1}
}

all.sex <- as.data.frame(cbind( sex.38fc4, sex.8a467, sex.d516d, sex.f7f7c,sex.1e6ee))
new.train <- cbind(all.age,all.sex)
```

##dealing with province
```{r}
province = train$province
province_union = union(train$province,test$province)
province_union
##create a data frame containing all union province 
province_matrix = as.data.frame(matrix(ncol = length(province_union), nrow = length(province)))

##crreate a array of each feature in province
feature = c()
for (each_province in province_union) {feature = append(feature,paste0('province.',each_province))}

colnames(province_matrix) = feature

for (i in 1:length(province)) {
  for (j in 1:length(feature)) {
    if (grepl(province[i],feature[j])) {
      province_matrix[i,j] = 1
    }
    else {province_matrix[i,j] = 0}
  }
}
new.train <- cbind(new.train,province_matrix)
```

##dealing with country

```{r}
country = train$country
country_union = union(train$country,test$country)
country_union
##create a data frame containing all union country 
country_matrix = as.data.frame(matrix(ncol = length(country_union), nrow = length(country)))

##crreate a array of each feature in country
feature = c()
for (each_country in country_union) {feature = append(feature,paste0('country.',each_country))}

colnames(country_matrix) = feature

for (i in 1:length(country)) {
  for (j in 1:length(feature)) {
    if (grepl(country[i],feature[j])) {
      country_matrix[i,j] = 1
    }
    else {country_matrix[i,j] = 0}
  }
}
new.train <- cbind(new.train,country_matrix)
```

##dealing with V1

```{r}
V1 = train$V1
V1_union = union(train$V1,test$V1)
V1_union
##create a data frame containing all union V1 
V1_matrix = as.data.frame(matrix(ncol = length(V1_union), nrow = length(V1)))

##crreate a array of each feature in V1
feature = c()
for (each_V1 in V1_union) {feature = append(feature,paste0('V1.',each_V1))}

colnames(V1_matrix) = feature

for (i in 1:length(V1)) {
  for (j in 1:length(feature)) {
    if (grepl(V1[i],feature[j])) {
      V1_matrix[i,j] = 1
    }
    else {V1_matrix[i,j] = 0}
  }
}
new.train <- cbind(new.train,V1_matrix)
```
##dealing with confirmed
##we convert confirmed date to numeric value




```{r}
confirmed = train$confirmed
for (i in 1:length(confirmed)){
  confirmed[i]=as.POSIXct(confirmed[i], format="%d.%m.%y")
}
confirmed = as.numeric(confirmed)
mu <- mean(confirmed[!is.na(confirmed)])
library(tidyverse)
confirmed = replace_na(confirmed,mu)
new.train <- cbind(new.train,confirmed)
```

##dealing with sympotoms

```{r}
##1. pre-processiong with text data 
#TODO: (optional) add feature no_symptoms
# train symptoms
train_symptoms=as.data.frame(train$symptoms)
#split string by ';'
library('tidyverse')
train_symptoms=as.data.frame(separate_rows(train_symptoms, 1, sep = ";", convert = FALSE))
colnames(train_symptoms) = c('train_symptoms')


for (i in 1:nrow(train_symptoms)){
  ## TODO: another way to extract feature by particular temp
  if (grepl('fever',train_symptoms[i,1])) {train_symptoms[i,1] = 'fever'}
  
  #remove leading space and trail space
  train_symptoms[i,1] = gsub("^\\s+|\\s+$", "", train_symptoms[i,1])
}

# test symptoms
test_symptoms=as.data.frame(test$symptoms)
#split string by ';'
test_symptoms=as.data.frame(separate_rows(test_symptoms, 1, sep = ";", convert = FALSE))
colnames(test_symptoms) = c('test_symptoms')
for (i in 1:nrow(test_symptoms)){
  ## TODO: another way to extract feature by particular temp
  if (grepl('fever',test_symptoms[i,1])) {test_symptoms[i,1] = 'fever'}
  
  #remove leading space and trail space
  test_symptoms[i,1] = gsub("^\\s+|\\s+$", "", test_symptoms[i,1])
}


```

```{r}
##extract feature from train data
#Find interection of symptoms in train and test
symptoms_intersect=intersect(train_symptoms$train_symptoms,test_symptoms$test_symptoms)
symptoms_intersect

#here we want to remove missing value in intersect array
symptoms_intersect = symptoms_intersect[-4]
symptoms_intersect

symptoms = train$symptoms
##create a data frame containing all intersect V1 
symptoms_matrix = as.data.frame(matrix(ncol = length(symptoms_intersect), nrow = length(symptoms)))

##crreate a array of each feature in V1
feature = c()
for (each_symptoms in symptoms_intersect) {feature = append(feature,paste0('symptoms.',each_symptoms))}

colnames(symptoms_matrix) = feature

for (i in 1:length(symptoms)) {
  for (j in 1:length(feature)) {
    if (grepl(symptoms_intersect[j],symptoms[i])) {
      symptoms_matrix[i,j] = 1
    }
    else {symptoms_matrix[i,j] = 0}
  }
}
##keeps only fever and cough
##add duration and symptoms.feature in new.train
duration = train$duration
new.train <- cbind(new.train,symptoms_matrix[,c(4,5)],duration)
```

```{r}
write.table(new.train, file = 'cleaned_train.txt', sep= ',')
head(new.train)
```

