---
title: "Untitled"
author: "Ao Tang"
date: "2020/10/6"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
train <- read.table('train2.txt',sep = ',',header = TRUE, fill = TRUE)
test <- read.table('test2.txt',sep = ',',header = TRUE, fill = TRUE)

train_chris <- read.table('cleaned_train.csv',sep = ',',header = TRUE, fill = TRUE)
test_chris <- read.table('cleaned_test.csv',sep = ',',header = TRUE, fill = TRUE)

train_ao <- read.table('cleaned_train.txt',sep = ',',header = TRUE, fill = TRUE)
test_ao <- read.table('cleaned_test.txt',sep = ',',header = TRUE, fill = TRUE)
```


```{r}
###merge add city 
temp = as.data.frame(table(train$city))
most_freq = temp[order(-temp$Freq),]
most_freq[1:5,1]

train_chris$city.38fc4 = train_ao$city.38fc4
train_chris$city.6d709 = train_ao$city.6d709
train_chris$city.247e5 = train_ao$city.247e5
train_chris$city.d7cac = train_ao$city.d7cac
train_chris$city.2720c = train_ao$city.2720c
```
```{r}
###merge add country

temp = as.data.frame(table(train$country))
most_freq = temp[order(-temp$Freq),]
most_freq[1:5,1]

train_chris$country.59dcd = train_ao$country.59dcd
train_chris$country.fb9d7 = train_ao$country.fb9d7
train_chris$country.c263d = train_ao$country.c263d
train_chris$country.d019a = train_ao$country.d019a
train_chris$country.38fc4 = train_ao$country.38fc4
```


```{r}
###merge add country

temp = as.data.frame(table(train$V1))
most_freq = temp[order(-temp$Freq),]
most_freq[1:5,1]

train_chris$V1.b6ab9 = train_ao$V1.b6ab9
train_chris$V1.35843 = train_ao$V1.35843
train_chris$V1.d68ec = train_ao$V1.d68ec
train_chris$V1.dd554 = train_ao$V1.dd554
train_chris$V1.10775 = train_ao$V1.10775


train_chris$symptoms.fever = train_ao$symptoms.fever
train_chris$symptoms.cough = train_ao$symptoms.cough
```


##we convert confirmed date to numeric value
```{r}
confirmed = train$confirmed
for (i in 1:length(confirmed)){
  confirmed[i]=as.POSIXct(confirmed[i], format='%d.%m.%Y')
  if (is.na(confirmed[i])){confirmed[i] = 'null'}
  }
confirmed = as.numeric(confirmed)
mu <- mean(confirmed[!is.na(confirmed)])
library(tidyverse)
confirmed = replace_na(confirmed,mu)
train_chris$confirmed=confirmed
```

#extract extra feature: 
```{r}
#confirmed = replace_na(confirmed,mu)
#train_chris$diff_day = difftime(strptime(train$confirmed, , format="%d.%m.%Y"),strptime('01.01.2020' , format="%d.%m.%Y"), units = 'days')
```





test set 
---
```{r}
###merge add city 
temp = as.data.frame(table(test$city))
most_freq = temp[order(-temp$Freq),]
most_freq[1:5,1]

test_chris$city.38fc4 = test_ao$city.38fc4
test_chris$city.6d709 = test_ao$city.6d709
test_chris$city.247e5 = test_ao$city.247e5
test_chris$city.d7cac = test_ao$city.d7cac
test_chris$city.2720c = test_ao$city.2720c
```
```{r}
###merge add country

temp = as.data.frame(table(test$country))
most_freq = temp[order(-temp$Freq),]
most_freq[1:5,1]

test_chris$country.59dcd = test_ao$country.59dcd
test_chris$country.fb9d7 = test_ao$country.fb9d7
test_chris$country.c263d = test_ao$country.c263d
test_chris$country.d019a = test_ao$country.d019a
test_chris$country.38fc4 = test_ao$country.38fc4
```


```{r}
###merge add country

temp = as.data.frame(table(test$V1))
most_freq = temp[order(-temp$Freq),]
most_freq[1:5,1]

test_chris$V1.b6ab9 = test_ao$V1.b6ab9
test_chris$V1.35843 = test_ao$V1.35843
test_chris$V1.d68ec = test_ao$V1.d68ec
test_chris$V1.dd554 = test_ao$V1.dd554
test_chris$V1.10775 = test_ao$V1.10775


test_chris$symptoms.fever = test_ao$symptoms.fever
test_chris$symptoms.cough = test_ao$symptoms.cough
```


##we convert confirmed date to numeric value
```{r}
confirmed = test$confirmed
for (i in 1:length(confirmed)){
  confirmed[i]=as.POSIXct(confirmed[i], format="%d.%m.%Y")
  if (is.na(confirmed[i])){confirmed[i] = 'null'}
  }
confirmed = as.numeric(confirmed)
mu <- mean(confirmed[!is.na(confirmed)])
library(tidyverse)
confirmed = replace_na(confirmed,mu)
test_chris$confirmed=confirmed
```

#extract extra feature: 
```{r}
#confirmed = replace_na(confirmed,mu)
#test_chris$diff_day = difftime(strptime(test$confirmed, , format="%d.%m.%Y"),strptime('01.01.2020', format="%d.%m.%Y"), units = 'days')
```



```{r}

train_chris= subset(train_chris, select = -c(country,V1))
test_chris= subset(test_chris, select = -c(country,V1))

model  = lm(duration~.,data = train_chris)


pred = predict(model, test_chris)
pred
```



```{r}
model2 = lm(duration~confirmed+age,data = train_chris)
model2

age = train_chris$age+ 1 
confirmed = train_chris$confirmed+ 3600

new_data =as.data.frame(cbind(confirmed,age))

pred = predict(model2, new_data)
pred

new_train = train_chris
new_train$age = new_data$age
new_train$confirmed = new_data$confirmed
new_train$duration = pred

new_train = rbind(train_chris,new_train)
```


```{r}
model  = lm(duration~.,data = new_train)


pred1 = predict(model, test_chris)
pred1
```



```{r}
library(randomForest)
rf = randomForest(duration ~ ., data = new_train)
pred2 = predict(rf, test_chris)
pred2
```

```{r}
#kaggle = read.table(file = 'baseline2.txt', sep = ',', header = T, row.names = NULL)

#kaggle$duration = pred

#write.table(kaggle, file = 'kaggle1.txt', sep = ',', quote = F, row.name = FALSE)
```

```{r}
rf = randomForest(duration ~ ., data = train_ao)
pred3 = predict(rf, test_ao)
pred3



pred = 0.5*pred2 + 0.5*pred3
pred
```



























